language: ruby
cache: bundler
sudo: false
rvm: 2.5
install:
- gem install bundler
- bundle install
script:
- bundle exec jekyll build
after_success: |
  cd "$TRAVIS_BUILD_DIR"
  git init
  git checkout -b master
  git add .
  git -c user.name='travis' -c user.email='travis' commit -m init
  # Make sure to make the output quiet, or else the API token will leak!
  # This works because the API key can replace your password.
  git push -f -q https://<me>:$github_token@github.com/<me>/<myrepo>-gh-pages gh-pages &>/dev/null
  cd "$TRAVIS_BUILD_DIR"
branches:
  only: dev
deploy:
  provider: pages
  target_branch: master
  edge: true
  skip-cleanup: true
  keep-history: true
  github_token: $github_token
  on:
    repo: Martin005/Martin005.github.io
    branch: master
  committer-from-gh: true
