language: ruby
cache: bundler
sudo: false
rvm: 2.5
install:
- gem install bundler
- bundle install
script:
- bundle exec jekyll build
after_success:
- touch ./_site/.nojekyll
deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  on:
    branch: master
  local-dir: _site
  committer-from-gh: true
env:
  global:
    secure: n59Et8cMJkymq/Snhswu2nTQKOHENFlgZMZwAV+oRnQQqVLT8AH25lB+9/QE1YWdh+CI+3vs0gK7euGkNNIQxAFosnGeIAHhPC7P5qtP79WjBcvH4KdrwYn8JosNCatkzf4ZlUZvsaWig4ZQR0d0xMWzGoD+RLOsvCntPvpm30/UtnKM+XYyR3Ub5K44KF7wZKSnbVI+1gYquVUD1xmjFRNexm7hQdKyu1/Ab+WPwbiE0+XwAX1nhJUQiOuZmw3d1L7vzEqfatl/ybCQs76RaWbklugRj9X6aaj/M3r1V/p+7TEfjumxIsha80EKVPhEbIJaBWoNOSWDmXYp1MGoU4KdacAvebcr4upXsUsekii+bIBstqy+l60sHtIrfYqgGYlrziLmC4un9ZmK1majdHYqpEGhkP+yZUULElpuEtHgJ5RZIFOJj0aLYtBCH0GVG8uBp9fdFMDL+0zE/6KsM/ovlwqKeJZG6we8rGrQWvgKhEMx43MWquXJ7Z4bDZjEDp7jEGnlX8cUntO5PkpFAhXP0qpIbVz0XribVbJIVnwVBruEWtWJlDII8xwHK5x5FeE/yiJK1FXg0kZskMXnE15FMSx1SvWjKIXCIMJCRJ6RGlC2FISZ8/abqwWuOHK2/FUB7aQoc+sjViV3NJRudn6sP/8Z2DxnStg3naRgwo4=
