language: ruby
cache: bundler
sudo: false
rvm: 2.5
install:
- gem install bundler
- bundle install
script:
- bundle exec jekyll build
after_success:
- touch ./_site/.nojekyll
deploy:
  provider: releases
  edge: true
  skip-cleanup: true
  keep-history: true
  github_token: $github_token
  on:
    repo: Martin005/Martin005.github.io
    branch: master
  local-dir: _site
  committer-from-gh: true
